language: php
php:
  - '7.1'

sudo: false

before_install:
  - composer self-update
install:
  - composer install
script:
  - ./vendor/bin/php-cs-fixer fix . -v --dry-run --diff --using-cache=no
  - ./vendor/bin/phpunit --coverage-clover coverage.xml
after_success:
  - travis_retry ./vendor/bin/php-coveralls -x coverage.xml

cache:
  directories:
    - $HOME/.composer/cache/files